baseURL = "https://uikesaksikuntoon.fi"
languageCode = "fi"
title = "Ui kesäksi kuntoon"
search_console = "4zn8Li9QQjD_TQ6d-XHcyr9sKLDsF9q3h9caEkV-GEY"
theme = "ananke"
pluralizelisttitles = false
summaryLength = 15
show_reading_time = true


logo = "#"

MetaDataFormat = "yaml"
DefaultContentLanguage = "fi"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 2

  pageNotFoundTitle = "404 - Sivua ei löytynyt"
  disableHugoGeneratorInject = true
